src/Entity/Pret.php
<?php

namespace App\Entity;

use App\Repository\PretRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PretRepository::class)]
class Pret
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_debut = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_retour = null;

    #[ORM\ManyToOne(inversedBy: 'prets')]
    private ?Materiel $id_materiel = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateRetour(): ?\DateTimeInterface
    {
        return $this->date_retour;
    }

    public function setDateRetour(\DateTimeInterface $date_retour): self
    {
        $this->date_retour = $date_retour;

        return $this;
    }

    public function getIdMateriel(): ?Materiel
    {
        return $this->id_materiel;
    }

    public function setIdMateriel(?Materiel $id_materiel): self
    {
        $this->id_materiel = $id_materiel;

        return $this;
    }

    public function getIdMaterielId()
    {
        return $this->id_materiel_id;
    }
}

src/Form/PretType.php
<?php

namespace App\Form;

use App\Entity\Pret;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PretType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('date_debut')
            ->add('date_retour')
            ->add('id_materiel')
            ->add('id_materiel_id');
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Pret::class,
        ]);
    }
}

src/Controller/PretController.php
<?php

namespace App\Controller;

use App\Entity\Pret;
use App\Entity\Materiel;
use App\Form\PretType;
use App\Repository\PretRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/pret')]
class PretController extends AbstractController
{
    #[Route('/', name: 'app_pret_index', methods: ['GET'])]
    public function index(PretRepository $pretRepository): Response
    {
        return $this->render('pret/index.html.twig', [
            'prets' => $pretRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_pret_new', methods: ['GET', 'POST'])]
    public function new(Request $request, PretRepository $pretRepository): Response
    {
        $pret = new Pret();
        $form = $this->createForm(PretType::class, $pret);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $pretRepository->save($pret, true);

            return $this->redirectToRoute('app_pret_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('pret/new.html.twig', [
            'pret' => $pret,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_pret_show', methods: ['GET'])]
    public function show(Pret $pret, Materiel $materiel): Response
    {
        return $this->render('pret/show.html.twig', [
            'pret' => $pret,
            'materiel' => $materiel,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_pret_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Pret $pret, PretRepository $pretRepository): Response
    {
        $form = $this->createForm(PretType::class, $pret);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $pretRepository->save($pret, true);

            return $this->redirectToRoute('app_pret_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('pret/edit.html.twig', [
            'pret' => $pret,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_pret_delete', methods: ['POST'])]
    public function delete(Request $request, Pret $pret, PretRepository $pretRepository): Response
    {
        if ($this->isCsrfTokenValid('delete' . $pret->getId(), $request->request->get('_token'))) {
            $pretRepository->remove($pret, true);
        }

        return $this->redirectToRoute('app_pret_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/pret/_delete_form.html.twig
<form method="post" action="{{ path('app_pret_delete', {'id': pret.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ pret.id) }}">
    <button class="btn">Delete</button>
</form>

templates/pret/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/pret/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Pret{% endblock %}

{% block body %}
    <h1>Edit Pret</h1>

    {{ include('pret/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_pret_index') }}">back to list</a>

    {{ include('pret/_delete_form.html.twig') }}
{% endblock %}

templates/pret/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Pret index{% endblock %}

{% block body %}
    <h1>Pret index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Date_debut</th>
                <th>Date_retour</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for pret in prets %}
            <tr>
                <td>{{ pret.id }}</td>
                <td>{{ pret.dateDebut ? pret.dateDebut|date('Y-m-d') : '' }}</td>
                <td>{{ pret.dateRetour ? pret.dateRetour|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('app_pret_show', {'id': pret.id}) }}">show</a>
                    <a href="{{ path('app_pret_edit', {'id': pret.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_pret_new') }}">Create new</a>
{% endblock %}

templates/pret/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Pret{% endblock %}

{% block body %}
    <h1>Create new Pret</h1>

    {{ include('pret/_form.html.twig') }}

    <a href="{{ path('app_pret_index') }}">back to list</a>
{% endblock %}

templates/pret/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Pret
{% endblock %}

{% block body %}
	<h1>Pret</h1>

	<table class="table">
		<tbody>
			<tr>
				<th>Id</th>
				<td>{{ pret.id }}</td>
			</tr>
			<tr>
				<th>Date_debut</th>
				<td>{{ pret.dateDebut ? pret.dateDebut|date('Y-m-d') : '' }}</td>
			</tr>
			<tr>
				<th>Date_retour</th>
				<td>{{ pret.dateRetour ? pret.dateRetour|date('Y-m-d') : '' }}</td>
			</tr>
			<tr>
				<th></th>
				<td>{{ materiel.id_materiel_id }}</td>
			</tr>
		</tbody>
	</table>

	<a href="{{ path('app_pret_index') }}">back to list</a>

	<a href="{{ path('app_pret_edit', {'id': pret.id}) }}">edit</a>

	{{ include('pret/_delete_form.html.twig') }}
{% endblock %}